#!/bin/bash
# Installs Refrain as a macOS launchd LaunchAgent: it runs in the background
# with no Terminal window, starts automatically at login, and relaunches itself
# if it ever crashes. Double-click this file to run it.
# To undo, double-click uninstall-launchagent.command.
#
# There is also a button for this on the Health screen, which does exactly the
# same thing. This script is for setting it up before anyone has opened the app.
set -e
cd "$(dirname "$0")/.."

# shellcheck source=find-node.sh
. "$(dirname "$0")/find-node.sh"

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required but wasn't found on this machine."
  echo "Install it from https://nodejs.org (the LTS version), then re-run this."
  echo
  echo "No administrator password? Node can be installed into your home folder"
  echo "instead, with no admin rights — see the Installing section of README.md."
  read -r -p "Press Enter to close..."
  exit 1
fi

# A LaunchAgent that starts before the dependencies exist is a job that fails
# at every login, so install them here rather than letting launchd discover it.
if [ ! -d node_modules ]; then
  echo "Installing dependencies (first run only)..."
  npm install
fi

# The plist is generated by server/autostart.js -- the same code the Health
# screen's button uses, and the code the tests cover. Writing a second copy of
# that XML here is how the two would drift apart.
node --input-type=module -e '
  import { install } from "./server/autostart.js";
  const port = process.env.PORT || 9999;
  const state = await install({ appDir: process.cwd(), port });
  console.log("");
  console.log("Done. Refrain now runs in the background and starts at login.");
  console.log("  Settings file: " + state.plistPath);
  console.log("  Logs:          logs/refrain.out.log (and refrain.err.log)");
'

echo
echo "If you previously started Refrain with start.command or added it as a"
echo "Login Item, remove that now. If one is still running, the background copy"
echo "stands down rather than fighting over the port — it takes over at the"
echo "next login, or as soon as you quit the other one."
echo
echo "A LaunchAgent only starts once this account logs in. For a hands-free"
echo "recovery after a full reboot, also turn on automatic login in"
echo "System Settings > Users & Groups."
read -r -p "Press Enter to close..."
